CREATE TABLE "GCG_5841_COPY_RT_INS"(
 "USER_NO" CHAR(8),
 "TERMINAL_NO" CHAR(3),
 "LINE_SEQUENCE" INTEGER,
 "INSPECTION" LONGVARCHAR,
 "METHOD" LONGVARCHAR,
 "FREQUENCY" LONGVARCHAR,
 "NON_CONFORM" LONGVARCHAR );
