CREATE TABLE "GCG_5841_RT_INSP"(
 "ROUTER" CHAR(50),
 "LINE_ROUTER" CHAR(50),
 "LINE_SEQUENCE" INTEGER,
 "INSTRUCTIONS" LONGVARCHAR,
 "INSPECTION" LONGVARCHAR,
 "METHOD" LONGVARCHAR,
 "FREQUENCY" LONGVARCHAR,
 "NON_CONFORM" LONGVARCHAR);
