CREATE TABLE "GCG_5841_WO_INSP"(
 "WORK_ORDER" CHAR(50),
 "WO_SUFF" CHAR(50),
 "WO_SEQUENCE" CHAR(50),
 "LINE_SEQUENCE" INTEGER,
 "INSTRUCTIONS" LONGVARCHAR,
 "INSPECTION" LONGVARCHAR,
 "METHOD" LONGVARCHAR,
 "FREQUENCY" LONGVARCHAR,
 "NON_CONFORM" LONGVARCHAR );